CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    summary VARCHAR(320) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(80) NOT NULL,
    tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    views BIGINT NOT NULL DEFAULT 0,
    helpful_count BIGINT NOT NULL DEFAULT 0,
    not_helpful_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    search_vector TSVECTOR NOT NULL DEFAULT ''::TSVECTOR,
    CONSTRAINT ck_articles_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT ck_articles_views CHECK (views >= 0),
    CONSTRAINT ck_articles_feedback CHECK (helpful_count >= 0 AND not_helpful_count >= 0)
);

CREATE UNIQUE INDEX uq_articles_slug_lower ON articles (LOWER(slug));
CREATE INDEX ix_articles_status_updated ON articles (status, updated_at DESC);
CREATE INDEX ix_articles_category_status ON articles (LOWER(category), status);
CREATE INDEX ix_articles_popular ON articles (status, views DESC);
CREATE INDEX ix_articles_tags ON articles USING GIN (tags);
CREATE INDEX ix_articles_search_vector ON articles USING GIN (search_vector);

CREATE FUNCTION articles_search_vector_update() RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.search_vector :=
        SETWEIGHT(TO_TSVECTOR('english', COALESCE(NEW.title, '')), 'A') ||
        SETWEIGHT(TO_TSVECTOR('english', COALESCE(NEW.summary, '')), 'B') ||
        SETWEIGHT(TO_TSVECTOR('english', COALESCE(NEW.category, '')), 'B') ||
        SETWEIGHT(TO_TSVECTOR('english', COALESCE(ARRAY_TO_STRING(NEW.tags, ' '), '')), 'B') ||
        SETWEIGHT(TO_TSVECTOR('english', COALESCE(NEW.content, '')), 'C');
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_articles_search_vector
BEFORE INSERT OR UPDATE OF title, summary, content, category, tags
ON articles
FOR EACH ROW
EXECUTE FUNCTION articles_search_vector_update();

CREATE TABLE search_query_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query VARCHAR(200) NOT NULL,
    result_count BIGINT NOT NULL,
    searched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_search_query_result_count CHECK (result_count >= 0)
);

CREATE INDEX ix_search_query_logs_no_results
    ON search_query_logs (searched_at DESC)
    WHERE result_count = 0;

